### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by chaabaj**
#14 Should fix the issue by using withCancellation

withCancellation take a callback which return a boolean to tell if it should cancel or not.

```
const Test = () => {
   const ref = useRef(false)
   const [state, setState] = useState(1)
   const withCancel = withCancellation(() => ref.current, setState) // enable cancellation
   const dispatch = dispatcherFromReact(withCancel) // pass the setState with cancellation
  
   useEffect(() => {
       dispatch(addAsync) // will cancel automatically if ref.current is true
       setTimeout(() => navigate("/"), 400)
       return () => { ref.current = true }
   }, [])
}
```

### CODE REVIEW

**Comment by okupara** [comment]
sorry, I'm a little bit busy this week, I will reply the next week. 🙇

**Comment by okupara** [comment]
Ah, okay, (state) => null does nothing, I didn't know that. it will be working.

another question came to me, hydralibs provides childDispatch* methods, so this case can be possible,

```
const [state, setState] = useState({childDataUsingAsync: {}})
const parentDispatch = dispatcherFromReact(setState)
const childDispatch = childDispatch(parentDispatch, "childDataUsingAsync")

// using childDispatch in child component for async request
```

I don't have enough time to create an example for the situation, but a developer likely want to cancel childDispatch from child component, how can the developer cancel childDispatch without canceling parentDispatch itself?

**Comment by chaabaj** [comment]
That's a good question actually, we definitely need that, from the parent to the child too.
I will add it

**Comment by chaabaj** [comment]
Closing this PR since there is no activity

**Pull request closed without merging**
